const SET_USER_VALUE_WORK = 'SET_USER_WALUE_WORK';
const SET_USER_VALUE_PRICE = 'SET_USER_WALUE_PRICE';
const SET_NEW_WORK = 'SET_NEW_WORK';
const DELETE_WORK = 'DELETE_WORK';
const EDIT_OLD_WORK = 'EDIT_OLD_WORK';
const SET_USER_FILTER = 'SET_USER_FILTER'

export {SET_USER_VALUE_PRICE, SET_USER_VALUE_WORK, SET_NEW_WORK, DELETE_WORK, EDIT_OLD_WORK, SET_USER_FILTER}